CREATE SCHEMA weather


-- auto generated
CREATE TABLE weather.cities (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	name varchar(255) NULL,
	CONSTRAINT cities_pkey PRIMARY KEY (id)
);

-- Ülkeler
INSERT INTO weather.cities (name) VALUES ('New Delhi');
INSERT INTO weather.cities (name) VALUES ('New York');
INSERT INTO weather.cities (name) VALUES ('Paris');

-- Türkiye'deki iller listesi
INSERT INTO weather.cities (name) VALUES ('Adana');
INSERT INTO weather.cities (name) VALUES ('Adıyaman');
INSERT INTO weather.cities (name) VALUES ('Afyonkarahisar');
INSERT INTO weather.cities (name) VALUES ('Ağrı');
INSERT INTO weather.cities (name) VALUES ('Amasya');
INSERT INTO weather.cities (name) VALUES ('Ankara');
INSERT INTO weather.cities (name) VALUES ('Antalya');
INSERT INTO weather.cities (name) VALUES ('Artvin');
INSERT INTO weather.cities (name) VALUES ('Aydın');
INSERT INTO weather.cities (name) VALUES ('Balıkesir');
INSERT INTO weather.cities (name) VALUES ('Bilecik');
INSERT INTO weather.cities (name) VALUES ('Bingöl');
INSERT INTO weather.cities (name) VALUES ('Bitlis');
INSERT INTO weather.cities (name) VALUES ('Bolu');
INSERT INTO weather.cities (name) VALUES ('Burdur');
INSERT INTO weather.cities (name) VALUES ('Bursa');
INSERT INTO weather.cities (name) VALUES ('Çanakkale');
INSERT INTO weather.cities (name) VALUES ('Çankırı');
INSERT INTO weather.cities (name) VALUES ('Çorum');
INSERT INTO weather.cities (name) VALUES ('Denizli');
INSERT INTO weather.cities (name) VALUES ('Diyarbakır');
INSERT INTO weather.cities (name) VALUES ('Edirne');
INSERT INTO weather.cities (name) VALUES ('Elazığ');
INSERT INTO weather.cities (name) VALUES ('Erzincan');
INSERT INTO weather.cities (name) VALUES ('Erzurum');
INSERT INTO weather.cities (name) VALUES ('Eskişehir');
INSERT INTO weather.cities (name) VALUES ('Gaziantep');
INSERT INTO weather.cities (name) VALUES ('Giresun');
INSERT INTO weather.cities (name) VALUES ('Gümüşhane');
INSERT INTO weather.cities (name) VALUES ('Hakkari');
INSERT INTO weather.cities (name) VALUES ('Hatay');
INSERT INTO weather.cities (name) VALUES ('Isparta');
INSERT INTO weather.cities (name) VALUES ('Mersin');
INSERT INTO weather.cities (name) VALUES ('İstanbul');
INSERT INTO weather.cities (name) VALUES ('İzmir');
INSERT INTO weather.cities (name) VALUES ('Kars');
INSERT INTO weather.cities (name) VALUES ('Kastamonu');
INSERT INTO weather.cities (name) VALUES ('Kayseri');
INSERT INTO weather.cities (name) VALUES ('Kırklareli');
INSERT INTO weather.cities (name) VALUES ('Kırşehir');
INSERT INTO weather.cities (name) VALUES ('Kocaeli');
INSERT INTO weather.cities (name) VALUES ('Konya');
INSERT INTO weather.cities (name) VALUES ('Kütahya');
INSERT INTO weather.cities (name) VALUES ('Malatya');
INSERT INTO weather.cities (name) VALUES ('Manisa');
INSERT INTO weather.cities (name) VALUES ('Kahramanmaraş');
INSERT INTO weather.cities (name) VALUES ('Mardin');
INSERT INTO weather.cities (name) VALUES ('Muğla');
INSERT INTO weather.cities (name) VALUES ('Muş');
INSERT INTO weather.cities (name) VALUES ('Nevşehir');
INSERT INTO weather.cities (name) VALUES ('Niğde');
INSERT INTO weather.cities (name) VALUES ('Ordu');
INSERT INTO weather.cities (name) VALUES ('Rize');
INSERT INTO weather.cities (name) VALUES ('Sakarya');
INSERT INTO weather.cities (name) VALUES ('Samsun');
INSERT INTO weather.cities (name) VALUES ('Siirt');
INSERT INTO weather.cities (name) VALUES ('Sinop');
INSERT INTO weather.cities (name) VALUES ('Sivas');
INSERT INTO weather.cities (name) VALUES ('Tekirdağ');
INSERT INTO weather.cities (name) VALUES ('Tokat');
INSERT INTO weather.cities (name) VALUES ('Trabzon');
INSERT INTO weather.cities (name) VALUES ('Tunceli');
INSERT INTO weather.cities (name) VALUES ('Şanlıurfa');
INSERT INTO weather.cities (name) VALUES ('Uşak');
INSERT INTO weather.cities (name) VALUES ('Van');
INSERT INTO weather.cities (name) VALUES ('Yozgat');
INSERT INTO weather.cities (name) VALUES ('Zonguldak');
INSERT INTO weather.cities (name) VALUES ('Aksaray');
INSERT INTO weather.cities (name) VALUES ('Bayburt');
INSERT INTO weather.cities (name) VALUES ('Karaman');
INSERT INTO weather.cities (name) VALUES ('Kırıkkale');
INSERT INTO weather.cities (name) VALUES ('Batman');
INSERT INTO weather.cities (name) VALUES ('Şırnak');
INSERT INTO weather.cities (name) VALUES ('Bartın');
INSERT INTO weather.cities (name) VALUES ('Ardahan');
INSERT INTO weather.cities (name) VALUES ('Iğdır');
INSERT INTO weather.cities (name) VALUES ('Yalova');
INSERT INTO weather.cities (name) VALUES ('Karabük');
INSERT INTO weather.cities (name) VALUES ('Kilis');
INSERT INTO weather.cities (name) VALUES ('Osmaniye');
INSERT INTO weather.cities (name) VALUES ('Düzce');